import axios from "axios";
import { assertPermission } from "@/services/sessionApi";
import { getProjectById } from "@/services/projectApi";
import { trackingFor, type ProjectTracking } from "@/services/mock/trackingMock";
import { type Role, type Permission } from "@/constants/permissions";

const useMock = import.meta.env.VITE_USE_MOCK !== "false";
const trackingEndpoint = import.meta.env.VITE_TRACKING_API_ENDPOINT as string | undefined;
const storageEndpoint = import.meta.env.VITE_STORAGE_UPLOAD_ENDPOINT as string | undefined;
const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || "http://localhost:8080/api", timeout: 8000 });
const updateKey = "mplads.tracking-updates.v1";
export type ProgressUpdatePayload = { physicalProgress: number; utilizedAmount: number; updateDate: string; remarks: string; document?: { name: string; type: string; size: number } };
export type ProgressUpdateResult = { source: "api" | "mock"; tracking: ProjectTracking; message: string };
function readUpdates() { try { return JSON.parse(window.localStorage.getItem(updateKey) || "{}") as Record<string, ProgressUpdatePayload[]>; } catch { return {}; } }
function mergeUpdate(base: ProjectTracking, update?: ProgressUpdatePayload): ProjectTracking { if (!update) return base; const financial = Math.min(100, Math.round((update.utilizedAmount / Math.max(base.sanctionedAmount, 1)) * 100)); return { ...base, physicalProgress: update.physicalProgress, financialProgress: financial, overallProgress: Math.round((update.physicalProgress + financial) / 2), utilizedAmount: update.utilizedAmount, remainingAmount: Math.max(base.sanctionedAmount - update.utilizedAmount, 0), lastUpdated: update.updateDate, remarks: [update.remarks, ...base.remarks], events: [{ id: `local-${update.updateDate}`, date: update.updateDate, title: "Agency progress update", detail: update.remarks, tone: "blue" }, ...base.events], documents: update.document ? [{ name: update.document.name, type: "Progress report", date: update.updateDate, status: "Available" }, ...base.documents] : base.documents }; }
function validate(payload: ProgressUpdatePayload, projectAmount: number) { if (!Number.isFinite(payload.physicalProgress) || payload.physicalProgress < 0 || payload.physicalProgress > 100) throw new Error("Physical progress must be between 0 and 100."); if (!Number.isFinite(payload.utilizedAmount) || payload.utilizedAmount < 0 || payload.utilizedAmount > projectAmount) throw new Error("Utilized amount must be between zero and the sanctioned amount."); if (!payload.updateDate || Number.isNaN(Date.parse(payload.updateDate))) throw new Error("Enter a valid update date."); if (payload.remarks.trim().length < 20) throw new Error("Remarks must contain at least 20 characters."); if (payload.document && payload.document.size > 5 * 1024 * 1024) throw new Error("Supporting document must be 5 MB or smaller."); }
export async function getProjectTracking(id: string): Promise<{ project: NonNullable<Awaited<ReturnType<typeof getProjectById>>>; tracking: ProjectTracking; source: "api" | "mock" } | null> { if (!useMock && trackingEndpoint) { const response = await api.get(`${trackingEndpoint}/${encodeURIComponent(id)}`); return { ...response.data, source: "api" }; } await new Promise((resolve) => window.setTimeout(resolve, 350)); const project = await getProjectById(id); if (!project) return null; const updates = readUpdates()[id] || []; return { project, tracking: updates.reduce((current, update) => mergeUpdate(current, update), trackingFor(project)), source: "mock" }; }
export async function submitProgressUpdate(id: string, payload: ProgressUpdatePayload, role: Role | null): Promise<ProgressUpdateResult> { const project = await getProjectById(id); if (!project) throw new Error("Project could not be found."); await assertPermission("EDIT_PROJECT" as Permission); validate(payload, project.amount); if (!useMock && trackingEndpoint) { let documentUrl: string | undefined; if (payload.document && storageEndpoint) documentUrl = storageEndpoint; const response = await api.post(`${trackingEndpoint}/${encodeURIComponent(id)}/updates`, { ...payload, documentUrl }); return { source: "api", tracking: response.data.tracking, message: "Progress update submitted to the monitoring service." }; } await new Promise((resolve) => window.setTimeout(resolve, 450)); const records = readUpdates(); records[id] = [...(records[id] || []), payload]; window.localStorage.setItem(updateKey, JSON.stringify(records)); const next = mergeUpdate(trackingFor(project), payload); return { source: "mock", tracking: next, message: "Progress update saved to the local mock record." }; }
export function trackingDataSource() { return !useMock && trackingEndpoint ? "api" : "mock"; }
export function storageDataSource() { return !useMock && storageEndpoint ? "configured" : "not-configured"; }
